In [0]:
/*    ==Parâmetros de Script==

    Versão do Servidor de Origem : SQL Server 2019 (15.0.2000)
    Edição do Mecanismo de Banco de Dados de Origem : Microsoft SQL Server Express Edition
    Tipo do Mecanismo de Banco de Dados de Origem : SQL Server Autônomo

    Versão do Servidor de Destino : SQL Server 2019
    Edição de Mecanismo de Banco de Dados de Destino : Microsoft SQL Server Express Edition
    Tipo de Mecanismo de Banco de Dados de Destino : SQL Server Autônomo
*/

# [dbo].[DependentesTB]

In [0]:
USE [TesteProgramacao]
GO

In [0]:
/****** Object:  Table [dbo].[DependentesTB]    Script Date: 20/03/2024 22:59:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DependentesTB](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FuncionarioID] [int] NULL,
	[Nome] [nchar](100) NULL,
	[DataNascimento] [date] NULL,
	[GeneroID] [int] NULL,
 CONSTRAINT [PK_DependentesTB] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[FuncionarioTB]

In [0]:
/****** Object:  Table [dbo].[FuncionarioTB]    Script Date: 20/03/2024 22:59:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FuncionarioTB](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [nchar](100) NULL,
	[DataNascimento] [date] NULL,
	[Salario] [decimal](18, 2) NULL,
	[GeneroID] [int] NULL,
 CONSTRAINT [PK_FuncionarioTB] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[GeneroTB]

In [0]:
/****** Object:  Table [dbo].[GeneroTB]    Script Date: 20/03/2024 22:59:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GeneroTB](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NomeGenero] [nchar](100) NULL,
 CONSTRAINT [PK_GeneroTB] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[DependentesTB]

In [0]:
SET IDENTITY_INSERT [dbo].[DependentesTB] ON 
INSERT [dbo].[DependentesTB] ([ID], [FuncionarioID], [Nome], [DataNascimento], [GeneroID]) VALUES (1, 3, N'Maykon Henrique                                                                                     ', CAST(N'2024-03-20' AS Date), 1)
SET IDENTITY_INSERT [dbo].[DependentesTB] OFF
GO

# [dbo].[FuncionarioTB]

In [0]:
SET IDENTITY_INSERT [dbo].[FuncionarioTB] ON 
INSERT [dbo].[FuncionarioTB] ([ID], [Nome], [DataNascimento], [Salario], [GeneroID]) VALUES (1, N'Jose                                                                                                ', CAST(N'1988-11-09' AS Date), CAST(1200.00 AS Decimal(18, 2)), 1)
INSERT [dbo].[FuncionarioTB] ([ID], [Nome], [DataNascimento], [Salario], [GeneroID]) VALUES (3, N'Amanda                                                                                              ', CAST(N'1952-11-09' AS Date), CAST(7500.50 AS Decimal(18, 2)), 2)
SET IDENTITY_INSERT [dbo].[FuncionarioTB] OFF
GO

# [dbo].[GeneroTB]

In [0]:
SET IDENTITY_INSERT [dbo].[GeneroTB] ON 
INSERT [dbo].[GeneroTB] ([ID], [NomeGenero]) VALUES (1, N'Masculino                                                                                           ')
INSERT [dbo].[GeneroTB] ([ID], [NomeGenero]) VALUES (2, N'Feminino                                                                                            ')
SET IDENTITY_INSERT [dbo].[GeneroTB] OFF
GO

# [dbo].[proc_contador]

In [0]:
/****** Object:  StoredProcedure [dbo].[proc_contador]    Script Date: 20/03/2024 22:59:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[proc_contador]
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
select Count(1) as 'Qtd',NomeGenero,DataNascimento from (
select GeneroTB.NomeGenero,YEAR(DependentesTB.DataNascimento) as 'DataNascimento'
from DependentesTB
inner join GeneroTB on GeneroTB.ID = DependentesTB.GeneroID
) as resultado
group by NomeGenero,DataNascimento

END
GO